easy_admin:
    entities:

        ####################
        ## Esteren Maps
        Factions:
            label: admin.maps.factions
            class: EsterenMaps\MapsBundle\Entity\Factions
            controller: EsterenMaps\MapsBundle\Controller\Admin\BaseMapAdminController
            list:
                fields:
                    - { property: id, label: 'admin.entities.common.id' }
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: description, label: 'admin.entities.common.description' }
                    - { property: book, label: 'admin.entities.common.book' }

            form:
                fields:
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: description, label: 'admin.entities.common.description' }
                    - { property: book, label: 'admin.entities.common.book' }

        Maps:
            label: admin.maps.maps
            class: EsterenMaps\MapsBundle\Entity\Maps
            controller: EsterenMaps\MapsBundle\Controller\Admin\BaseMapAdminController
            list:
                actions:
                    - edit
                    - { name: admin_esterenmaps_maps_maps_editInteractive, type: route, label: actions.interactive  }
                    - '-delete'
                fields:
                    - { property: id, label: 'admin.entities.common.id' }
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: nameSlug, label: 'admin.entities.common.nameSlug' }
                    - { property: maxZoom, label: 'admin.entities.factions.maxZoom' }
                    - { property: startZoom, label: 'admin.entities.factions.startZoom' }
                    - { property: startX, label: 'admin.entities.factions.startX' }
                    - { property: startY, label: 'admin.entities.factions.startY' }
            new:
                fields:
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: nameSlug, label: 'admin.entities.common.nameSlug' }
                    - { property: image, label: 'admin.entities.factions.image' }
                    - { property: description, label: 'admin.entities.common.description' }
                    - { property: maxZoom, label: 'admin.entities.factions.maxZoom' }
                    - { property: bounds, label: 'admin.entities.factions.bounds' }
                    - { property: startZoom, label: 'admin.entities.factions.startZoom' }
                    - { property: startX, label: 'admin.entities.factions.startX' }
                    - { property: startY, label: 'admin.entities.factions.startY' }
                    - { property: coordinatesRatio, label: 'admin.entities.factions.coordinatesRatio' }
            edit:
                fields:
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: nameSlug, label: 'admin.entities.common.nameSlug', type_options: { disabled: true, required: false } }
                    - { property: image, label: 'admin.entities.factions.image', type_options: { disabled: true, required: false } }
                    - { property: description, label: 'admin.entities.common.description' }
                    - { property: maxZoom, label: 'admin.entities.factions.maxZoom' }
                    - { property: bounds, label: 'admin.entities.factions.bounds' }
                    - { property: startZoom, label: 'admin.entities.factions.startZoom' }
                    - { property: startX, label: 'admin.entities.factions.startX' }
                    - { property: startY, label: 'admin.entities.factions.startY' }
                    - { property: coordinatesRatio, label: 'admin.entities.factions.coordinatesRatio' }

        Markers:
            label: admin.maps.markers
            class: EsterenMaps\MapsBundle\Entity\Markers
            controller: EsterenMaps\MapsBundle\Controller\Admin\BaseMapAdminController
            list:
                actions:
                    - '-delete'
                fields:
                    - { property: id, label: 'admin.entities.common.id' }
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: latitude, label: 'admin.entities.markers.latitude' }
                    - { property: longitude, label: 'admin.entities.markers.longitude' }
                    - { property: markerType, label: 'MarkersTypes' }
                    - property: webIcon
                      label: 'admin.entities.markers.web_icon'
                      type: image
            form:
                fields:
                    - property: name
                      label: 'admin.entities.common.name'
                      type_options:
                          required: true
                    - { property: description, label: 'admin.entities.common.description' }
                    - { property: markerType, label: 'MarkersTypes' }
                    - { property: faction, label: 'Factions' }
                    - property: latitude
                      label: 'admin.entities.markers.latitude'
                      type_options: { disabled: true, required: false }

                    - property: longitude
                      label: 'admin.entities.markers.longitude'
                      type_options: { disabled: true, required: false }

                    - property: altitude
                      label: 'admin.entities.markers.altitude'
                      type_options: { disabled: true, required: false }

                    - property: map
                      label: 'Maps'
                      type_options: { disabled: true, required: false }

        MarkersTypes:
            label: admin.maps.markers_types
            class: EsterenMaps\MapsBundle\Entity\MarkersTypes
            controller: EsterenMaps\MapsBundle\Controller\Admin\BaseMapAdminController
            list:
                actions:
                    - '-delete'
                fields:
                    - id
                    - name
                    - { property: webIcon, type: image, virtual: false } # FIXME
                    - markers
            form:
                fields: [ name, icon, markers ]

        Routes:
            label: admin.maps.routes
            class: EsterenMaps\MapsBundle\Entity\Routes
            controller: EsterenMaps\MapsBundle\Controller\Admin\BaseMapAdminController
            list:
                actions:
                    - '-delete'
                fields:
                    - { property: id, label: 'admin.entities.common.id' }
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: distance, label: 'admin.entities.routes.distance' }
                    - { property: description, label: 'admin.entities.common.description' }
                    - { property: routeType, label: 'RoutesTypes' }
                    - { property: markerStart, label: 'admin.entities.routes.markerStart' }
                    - { property: markerEnd, label: 'admin.entities.routes.markerEnd' }
            form:
                fields:
                    - { property: name,  label: 'admin.entities.common.name', type_options: { required: true } }
                    - { property: description, label: 'admin.entities.common.description' }
                    - { property: markerStart, label: 'admin.entities.routes.markerStart' }
                    - { property: markerEnd, label: 'admin.entities.routes.markerEnd' }
                    - { property: routeType, label: 'RoutesTypes' }
                    - { property: faction, label: 'Factions' }
                    - { property: guarded, label: 'admin.entities.routes.guarded' }
                    - { property: coordinates, label: 'admin.entities.common.coordinates', type_options: { disabled: true, required: false } }
                    - { property: map, label: 'Maps', type_options: { disabled: true, required: false } }

        RoutesTypes:
            label: admin.maps.routes_types
            class: EsterenMaps\MapsBundle\Entity\RoutesTypes
            controller: EsterenMaps\MapsBundle\Controller\Admin\BaseMapAdminController
            list:
                actions:
                    - '-delete'
                fields:
                    - { property: id, label: 'admin.entities.common.id' }
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: color, label: 'admin.entities.common.color' }
                    - { property: routes, label: 'Routes' }
            form:
                fields:
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: color, label: 'admin.entities.common.color' }

        Zones:
            label: admin.maps.zones
            class: EsterenMaps\MapsBundle\Entity\Zones
            controller: EsterenMaps\MapsBundle\Controller\Admin\BaseMapAdminController
            list:
                actions:
                    - '-delete'
                fields:
                    - { property: id, label: 'admin.entities.common.id' }
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: description, label: 'admin.entities.common.description' }
                    - { property: zoneType, label: 'ZonesTypes' }
                    - { property: map, label: 'Maps' }
                    - { property: faction, label: 'Factions' }
            form:
                fields:
                    - property: name
                      label: 'admin.entities.common.name'
                      type_options:
                          required: true
                    - { property: description, label: 'admin.entities.common.description' }
                    - { property: zoneType, label: 'ZonesTypes' }
                    - { property: faction, label: 'Factions' }
                    - property: coordinates
                      label: 'admin.entities.common.coordinates'
                      type_options:
                          disabled: true
                          required: false
                          attr: { readonly: readonly }
                    - property: map
                      label: 'Maps'
                      type_options:
                          disabled: true
                          required: false
                          attr: { readonly: readonly }

        ZonesTypes:
            label: admin.maps.zones_types
            class: EsterenMaps\MapsBundle\Entity\ZonesTypes
            controller: EsterenMaps\MapsBundle\Controller\Admin\BaseMapAdminController
            list:
                actions:
                    - '-delete'
                fields:
                    - { property: id, label: 'admin.entities.common.id' }
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: color, label: 'admin.entities.common.color' }
                    - { property: parent, label: 'admin.entities.zones_types.parent' }
                    - { property: zones, label: 'admin.entities.zones_types.zones' }
            form:
                fields:
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: color, label: 'admin.entities.common.color' }
                    - { property: parent, label: 'admin.entities.zones_types.parent' }

        TransportTypes:
            label: admin.maps.transports_types
            class: EsterenMaps\MapsBundle\Entity\TransportTypes
            controller: EsterenMaps\MapsBundle\Controller\Admin\TransportTypesController
            list:
                actions:
                    - '-delete'
                fields:
                    - { property: id, label: 'admin.entities.common.id' }
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: slug, label: 'admin.entities.common.slug' }
                    - { property: speed, label: 'admin.entities.transports.speed', format: '%.2f' }
                    - { property: description, label: 'admin.entities.common.description' }
            form:
                fields:
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: slug, label: 'admin.entities.common.slug' }
                    - { property: speed, label: 'admin.entities.transports.speed', help: '(Km/h)' }
                    - { property: description, label: 'admin.entities.common.description' }
                    - property: transportsModifiers
                      label: 'admin.entities.transports.modifiers'
                      type: 'Symfony\Component\Form\Extension\Core\Type\CollectionType'
                      type_options:
                          entry_type: 'EsterenMaps\MapsBundle\Form\TransportModifiersType'
